spring:
  application:
    name: orderservice
  kafka:
    bootstrap-servers: 159.89.225.129:9092
    order-topic: "order.created"

  cloud:
    config:
      uri: http://localhost:8888
      fail-fast: true

server:
  port: 8081